services:
  computeruse:
    build:
      dockerfile: Dockerfile
      context: computer-use-demo
    environment:
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
    ports:
      - 5900:5900
      - 8501:8501
      - 6080:6080
      - 8080:8080
    volumes:
      - ~/.anthropic:/home/computeruse/.anthropic
